version: "3.9"

services:
  postgres:
    container_name: my_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "topicstoredb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: my_api
    build:
      context: ../
      dockerfile: Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data: